#!/usr/bin/env python

import os
import subprocess
import sys


def run_command(command, path):
    print command
    subprocess.check_call(command.split(), cwd=path)


def run_tests(path):
    for filename in os.listdir(path):
        if filename.endswith('_unittest'):
            filename = os.path.join(os.curdir, filename)
            run_command(filename, path)


def main(args):
    targets = frozenset(args[1:])
    makefile = os.path.abspath('Makefile')
    for dirpath, dirnames, _ in os.walk('solved'):
        for dirname in sorted(dirnames):
            if targets and dirname not in targets:
                print '# SKIP %s' % dirname
                continue
            print '# JUDGE %s' % dirname
            path = os.path.join(dirpath, dirname)
            run_command('make -f %s unittests' % makefile, path)
            run_tests(path)
            run_command('make -f %s clean' % makefile, path)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
